import crypto from 'node:crypto';
import sql from 'mssql';
import { runMigrations } from '../../src/migrations/run-migrations.js';

const TABLES = [
    'idp_credentials', 'idp_service_keys', 'idp_verification_tokens', 'idp_oauth_clients',
    'idp_consents', 'idp_authorization_codes', 'idp_access_token_audit', 'idp_sessions',
    'idp_user_recovery_codes', 'idp_user_external_providers', 'idp_users',
];

const baseConfig = {
    server: process.env.MSSQL_TEST_HOST || '127.0.0.1',
    port: Number(process.env.MSSQL_TEST_PORT || 14330),
    user: process.env.MSSQL_TEST_USER || 'sa',
    password: process.env.MSSQL_TEST_PASSWORD || 'IdpCore_Test_Pass123!',
    options: { encrypt: false, trustServerCertificate: true },
};

/**
 * Connects to a real SQL Server instance (see ../../docker-compose.yml —
 * `docker compose up -d` before running tests) and creates a FRESH,
 * uniquely-named database for this call, then runs migrations against it.
 *
 * This per-call database is essential, not cosmetic: `node --test` runs
 * multiple test *files* concurrently by default, and unlike the Postgres/
 * DynamoDB adapters (each test file gets its own in-process pglite/dynalite
 * instance), there is no pure-JS/embeddable SQL Server — every test file
 * would otherwise share one physical database, and one file's
 * `truncateAll()` mid-run would silently wipe out another file's
 * in-progress rows. Confirmed empirically: running all repository test
 * files together without this produced several failures that vanished when
 * each file got its own database.
 *
 * One instance is meant to be shared across an entire test file via
 * `before`/`after`; call `truncateAll()` between tests within that file for
 * isolation.
 */
export async function buildTestDb() {
    const dbName = `idp_test_${crypto.randomBytes(6).toString('hex')}`;

    const admin = new sql.ConnectionPool({ ...baseConfig, database: 'master' });
    await admin.connect();
    // Database names can't be parameterized in DDL (T-SQL has no bind-
    // parameter support for identifiers) — safe here since dbName is
    // entirely generated by this function, never external input.
    await admin.request().query(`CREATE DATABASE [${dbName}]`);
    await admin.close();

    const pool = new sql.ConnectionPool({ ...baseConfig, database: dbName });
    await pool.connect();
    await runMigrations(pool);

    return {
        pool,
        // A second, independent pool config pointed at this same freshly-
        // created database — used by smoke-init.test.js, which needs
        // createMssqlStorage() to build its OWN pool (a real adapter never
        // shares a caller-supplied pool instance), while still hitting the
        // exact per-call isolated database this helper just migrated.
        poolConfig: { ...baseConfig, database: dbName },
        async truncateAll() {
            for (const table of TABLES) {
                await pool.request().query(`DELETE FROM dbo.${table}`);
            }
        },
        async stop() {
            await pool.close();
            const admin2 = new sql.ConnectionPool({ ...baseConfig, database: 'master' });
            await admin2.connect();
            await admin2.request().query(`ALTER DATABASE [${dbName}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [${dbName}];`);
            await admin2.close();
        },
    };
}

export { baseConfig };
